workspace:
  base: /build
  path: src/github.com/UKHomeOffice/oar-ui

pipeline:
  test:
      image: node:8
      commands:
        - npm install
        - npm run coverage
      when:
        event:
        - push
        - pull_request
        - tag

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      status:
        - failure
        - success
      event:
        - push
        - pull_request
        - tag

  build:
    image: docker:18.03.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_name
    commands:
      - docker build -t $${DOCKER_NAME} . --no-cache
    when:
      event:
        - push
        - pull_request
        - tag

  image_to_artifactory:
    image: docker:18.03.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_username
      - docker_password
      - docker_server
      - docker_group
      - docker_name
    commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} $${DOCKER_SERVER}
    - docker tag $${DOCKER_NAME} $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_BRANCH}
    - docker push $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_BRANCH}
    when:
      event: push

  tag_image_to_artifactory:
    image: docker:18.03.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_username
      - docker_password
      - docker_server
      - docker_group
      - docker_name
    commands:
    - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} $${DOCKER_SERVER}
    - docker tag $${DOCKER_NAME} $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_SHA}
    - docker push $${DOCKER_SERVER}/$${DOCKER_GROUP}/$${DOCKER_NAME}:$${DRONE_COMMIT_SHA}
    when:
      event: tag
