pipeline:

##### Build Docker image and push to Artifactory on commits / merges to "develop" #####

  develop_docker_build_and_push:
    image: docker:17.09.0-ce
    secrets:
      - docker_artifactory_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - IMAGE_NAME=oar-ui
    commands:
      - printf '%s\n' "$${DOCKER_ARTIFACTORY_PASSWORD}" | docker login --username "cba_robot" --password-stdin docker.digital.homeoffice.gov.uk
      - docker build
        --build-arg OAR_UI_BUILD_COMMIT_SHA="$${DRONE_COMMIT_SHA}"
        --build-arg OAR_UI_BUILD_CREATED="$${DRONE_BUILD_CREATED}"
        --build-arg OAR_UI_BUILD_NUMBER="$${DRONE_BUILD_NUMBER}"
        --tag docker.digital.homeoffice.gov.uk/cba/"$${IMAGE_NAME}":$${DRONE_COMMIT_SHA}
        --tag docker.digital.homeoffice.gov.uk/cba/"$${IMAGE_NAME}":latest
        ./
      - docker push docker.digital.homeoffice.gov.uk/cba/"$${IMAGE_NAME}":$${DRONE_COMMIT_SHA}
      - docker push docker.digital.homeoffice.gov.uk/cba/"$${IMAGE_NAME}":latest
    when:
      branch: develop
