version: '3'
networks:
 oar:

services:
  oar-ui:
    image: quay.io/ukhomeofficedigital/oar-ui:latest
    ports:
      - "80:8080"
    networks:
      - "oar"
  keycloak:
    image: quay.io/ukhomeofficedigital/oar-keycloak:latest
    ports:
      - "8081:8080"
    restart: always
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password123!
      - UI_URL=http://localhost:8081/
    networks:
      - "oar"
  postgres-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #- "./data:/var/lib/postgresql/data"
    networks:
      - "oar"
  postgrest:
    image: quay.io/ukhomeofficedigital/oar-postgrest:latest
    ports:
      - "3000:3000"
    links:
      - postgres-db:postgres      
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:password@postgres:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
    networks:
      - "oar"
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "8082:80"
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=oar@homeoffice.gov.uk"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    networks:
      - "oar"
  flyway-migrator:
    image: gsengun/flyway-postgres
    volumes:
      - flyway-data:/flyway/sql
      #- ./sql:/flyway/sql
    depends_on:
      - postgres-db
    command: postgres-db 5432 postgres password postgres oardb
    #command: postgres-db 5432 postgres secret postgres public
    networks:
      - "oar"
volumes:
  postgres-data: {}      
  flyway-data: {}      
  
