version: '3'
networks:
 ui:

services:
  web:
    image: quay.io/ukhomeofficedigital/oar-ui
    ports:
      - "80:8080"
    networks:
      - "ui"
  postgres-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    networks:
      - "ui"
  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - "PGADMIN_DEFAULT_EMAIL=oar@homeoffice.gov.uk.com"
      - "PGADMIN_DEFAULT_PASSWORD=password"
    ports:
      - "8081:80"
    networks:
      - "ui"
  flyway-migrator:
    image: gsengun/flyway-postgres
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres-db
    command: postgres-db 5432 postgres password
    #command: postgres-db 5432 postgres secret postgres public
    networks:
      - "ui"
  
